# CMake generated Testfile for 
# Source directory: C:/Users/User/Desktop/Pairing/buildsync-archicad-addon
# Build directory: C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/build-sdk-dialog
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(buildsync_core_tests "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/build-sdk-dialog/Debug/buildsync_core_tests.exe")
  set_tests_properties(buildsync_core_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;31;add_test;C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(buildsync_core_tests "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/build-sdk-dialog/Release/buildsync_core_tests.exe")
  set_tests_properties(buildsync_core_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;31;add_test;C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(buildsync_core_tests "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/build-sdk-dialog/MinSizeRel/buildsync_core_tests.exe")
  set_tests_properties(buildsync_core_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;31;add_test;C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(buildsync_core_tests "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/build-sdk-dialog/RelWithDebInfo/buildsync_core_tests.exe")
  set_tests_properties(buildsync_core_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;31;add_test;C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;0;")
else()
  add_test(buildsync_core_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(buildsync_sync_tests "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/build-sdk-dialog/Debug/buildsync_sync_tests.exe")
  set_tests_properties(buildsync_sync_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;35;add_test;C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(buildsync_sync_tests "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/build-sdk-dialog/Release/buildsync_sync_tests.exe")
  set_tests_properties(buildsync_sync_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;35;add_test;C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(buildsync_sync_tests "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/build-sdk-dialog/MinSizeRel/buildsync_sync_tests.exe")
  set_tests_properties(buildsync_sync_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;35;add_test;C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(buildsync_sync_tests "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/build-sdk-dialog/RelWithDebInfo/buildsync_sync_tests.exe")
  set_tests_properties(buildsync_sync_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;35;add_test;C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;0;")
else()
  add_test(buildsync_sync_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(buildsync_addon_shell_tests "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/build-sdk-dialog/Debug/buildsync_addon_shell_tests.exe")
  set_tests_properties(buildsync_addon_shell_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;39;add_test;C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(buildsync_addon_shell_tests "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/build-sdk-dialog/Release/buildsync_addon_shell_tests.exe")
  set_tests_properties(buildsync_addon_shell_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;39;add_test;C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(buildsync_addon_shell_tests "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/build-sdk-dialog/MinSizeRel/buildsync_addon_shell_tests.exe")
  set_tests_properties(buildsync_addon_shell_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;39;add_test;C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(buildsync_addon_shell_tests "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/build-sdk-dialog/RelWithDebInfo/buildsync_addon_shell_tests.exe")
  set_tests_properties(buildsync_addon_shell_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;39;add_test;C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;0;")
else()
  add_test(buildsync_addon_shell_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(buildsync_native_runtime_tests "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/build-sdk-dialog/Debug/buildsync_native_runtime_tests.exe")
  set_tests_properties(buildsync_native_runtime_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;43;add_test;C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(buildsync_native_runtime_tests "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/build-sdk-dialog/Release/buildsync_native_runtime_tests.exe")
  set_tests_properties(buildsync_native_runtime_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;43;add_test;C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(buildsync_native_runtime_tests "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/build-sdk-dialog/MinSizeRel/buildsync_native_runtime_tests.exe")
  set_tests_properties(buildsync_native_runtime_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;43;add_test;C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(buildsync_native_runtime_tests "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/build-sdk-dialog/RelWithDebInfo/buildsync_native_runtime_tests.exe")
  set_tests_properties(buildsync_native_runtime_tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;43;add_test;C:/Users/User/Desktop/Pairing/buildsync-archicad-addon/CMakeLists.txt;0;")
else()
  add_test(buildsync_native_runtime_tests NOT_AVAILABLE)
endif()
